################################################ UPDATED! ################################################
---

antora:
  name: modules
  dir: www
  modules:
    - name: module-01
      label: "Promoting our machine"
      solveButton: false
    - name: module-02
      label: "OUs, Users, and Groups"
      solveButton: false
    - name: module-03
      label: "Just a dash of PowerShell"
      solveButton: false

tabs:
  - name: AAP
    url: https://control-${guid}.${domain}/
    external: false
  - name: Windows
    url: https://windows-ironrdp-${guid}.${domain}/
    external: false
  - name: VS Code
    url: https://vscode-${guid}.${domain}
    external: true
  - name: Gitea
    url: https://gitea-${guid}.${domain}/
    modules:
      - module-01
